# Generated by Django 5.2.7 on 2025-11-07 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accion", models.CharField(max_length=255)),
                (
                    "tabla_afectada",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("registro_id_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "detalles_encrypted",
                    models.TextField(blank=True, db_column="detalles", null=True),
                ),
                ("ip_usuario", models.CharField(blank=True, max_length=45, null=True)),
                ("fecha_accion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "LogAuditoria",
                "ordering": ["-fecha_accion"],
            },
        ),
    ]
