# Generated by Django 5.2.7 on 2025-11-23 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticoCIE10",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Diagnóstico CIE-10",
                "verbose_name_plural": "Diagnósticos CIE-10",
                "db_table": "DiagnosticoCIE10",
            },
        ),
        migrations.CreateModel(
            name="Madre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ficha_clinica_numero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Ficha Clínica",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección de Residencia"
                    ),
                ),
                (
                    "ficha_clinica_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Dirección (Legado)",
                    ),
                ),
                (
                    "rut_hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("rut_encrypted", models.TextField(blank=True, null=True)),
                (
                    "nombre_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nombre_encrypted", models.TextField(blank=True, null=True)),
                (
                    "telefono_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telefono_encrypted", models.TextField(blank=True, null=True)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pertenece_pueblo_originario", models.BooleanField(default=False)),
                (
                    "prevision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FONASA", "FONASA"),
                            ("ISAPRE", "ISAPRE"),
                            ("PARTICULAR", "PARTICULAR"),
                            ("NINGUNA", "Ninguna"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("antecedentes_medicos", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="madres_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Registró",
                    ),
                ),
            ],
            options={
                "verbose_name": "Madre",
                "verbose_name_plural": "Madres",
                "db_table": "Madre",
            },
        ),
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_parto", models.DateTimeField()),
                ("edad_gestacional", models.IntegerField(blank=True, null=True)),
                (
                    "tipo_parto",
                    models.CharField(
                        choices=[
                            ("Eutócico", "Eutócico"),
                            ("Cesárea Electiva", "Cesárea Electiva"),
                            ("Cesárea Urgencia", "Cesárea Urgencia"),
                            ("Fórceps", "Fórceps"),
                            ("Ventosa", "Ventosa"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "anestesia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Epidural", "Epidural"),
                            ("Raquídea", "Raquídea"),
                            ("General", "General"),
                            ("Otra", "Otra"),
                            ("Ninguna", "Ninguna"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("partograma_data", models.JSONField(blank=True, null=True)),
                ("epicrisis_data", models.JSONField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "madre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partos",
                        to="core.madre",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parto",
                "verbose_name_plural": "Partos",
                "db_table": "Parto",
                "ordering": ["-fecha_parto"],
            },
        ),
        migrations.CreateModel(
            name="Indicacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medicamento", "Medicamento"),
                            ("procedimiento", "Procedimiento"),
                            ("cuidado", "Cuidado de Enfermería"),
                            ("dieta", "Dieta"),
                            ("reposo", "Reposo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("dosis", models.CharField(blank=True, max_length=100, null=True)),
                ("via", models.CharField(blank=True, max_length=100, null=True)),
                ("frecuencia", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicaciones",
                        to="core.parto",
                    ),
                ),
            ],
            options={
                "db_table": "Indicacion",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoReferencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mongodb_object_id", models.CharField(max_length=255, unique=True)),
                ("nombre_archivo", models.TextField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("EPICRISIS_PDF", "Epicrisis PDF"),
                            ("REPORTE_EXCEL", "Reporte Excel"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_generacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Referencia",
                "verbose_name_plural": "Documentos de Referencia",
                "db_table": "DocumentoReferencia",
            },
        ),
        migrations.CreateModel(
            name="PartoDiagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.diagnosticocie10",
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.parto"
                    ),
                ),
            ],
            options={
                "db_table": "PartoDiagnostico",
                "unique_together": {("parto", "diagnostico")},
            },
        ),
        migrations.AddField(
            model_name="parto",
            name="diagnosticos",
            field=models.ManyToManyField(
                through="core.PartoDiagnostico", to="core.diagnosticocie10"
            ),
        ),
        migrations.CreateModel(
            name="RecienNacido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rut_provisorio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estado_al_nacer",
                    models.CharField(
                        choices=[("Vivo", "Vivo"), ("Nacido Muerto", "Nacido Muerto")],
                        max_length=50,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("Indeterminado", "Indeterminado"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("peso_gramos", models.IntegerField(blank=True, null=True)),
                (
                    "talla_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("apgar_1_min", models.SmallIntegerField(blank=True, null=True)),
                ("apgar_5_min", models.SmallIntegerField(blank=True, null=True)),
                ("profilaxis_vit_k", models.BooleanField(default=False)),
                ("profilaxis_oftalmica", models.BooleanField(default=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recien_nacidos",
                        to="core.parto",
                    ),
                ),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recien_nacidos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recién Nacido",
                "verbose_name_plural": "Recién Nacidos",
                "db_table": "RecienNacido",
            },
        ),
        migrations.CreateModel(
            name="Correccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("fecha_correccion", models.DateTimeField(auto_now_add=True)),
                ("campo_corregido", models.CharField(max_length=100)),
                ("valor_original", models.TextField(blank=True)),
                ("valor_nuevo", models.TextField()),
                ("justificacion", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Corrección de Registro",
                "verbose_name_plural": "Correcciones de Registros",
                "db_table": "Correccion",
                "ordering": ["-fecha_correccion"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="Correccion_content_54f743_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Defuncion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_defuncion", models.DateTimeField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defunciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "causa_defuncion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.diagnosticocie10",
                    ),
                ),
                (
                    "madre",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defuncion",
                        to="core.madre",
                    ),
                ),
                (
                    "recien_nacido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defuncion",
                        to="core.reciennacido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defunción",
                "verbose_name_plural": "Defunciones",
                "db_table": "Defuncion",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recien_nacido__isnull", False),
                            ("madre__isnull", False),
                            _connector="OR",
                        ),
                        name="defuncion_recien_nacido_o_madre",
                    )
                ],
            },
        ),
    ]
