# Generated by Django 5.2.7 on 2025-11-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="madre",
            name="usuario_registro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="madres_registradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que Registró",
            ),
        ),
    ]
