# Generated by Django 5.2.7 on 2025-11-23 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("puede_crear_admision_madre", models.BooleanField(default=False)),
                ("puede_editar_admision_madre", models.BooleanField(default=False)),
                (
                    "puede_ver_lista_administrativa_madres",
                    models.BooleanField(default=False),
                ),
                ("puede_ver_dashboard_clinico", models.BooleanField(default=False)),
                ("puede_crear_parto", models.BooleanField(default=False)),
                ("puede_editar_parto", models.BooleanField(default=False)),
                (
                    "puede_ver_todos_partos",
                    models.BooleanField(
                        default=False,
                        help_text="Si no está marcado, solo ve sus propios registros",
                    ),
                ),
                ("puede_crear_editar_partograma", models.BooleanField(default=False)),
                ("puede_crear_editar_epicrisis", models.BooleanField(default=False)),
                ("puede_generar_reportes_rem", models.BooleanField(default=False)),
                ("puede_ver_auditoria", models.BooleanField(default=False)),
                ("puede_gestionar_usuarios", models.BooleanField(default=False)),
                ("puede_eliminar_registros", models.BooleanField(default=False)),
                (
                    "puede_anexar_correccion",
                    models.BooleanField(
                        default=False,
                        help_text="Permiso para anexar correcciones (ej. Médico)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "Rol",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=255, unique=True, verbose_name="RUT"),
                ),
                ("nombre_completo", models.TextField(verbose_name="Nombre Completo")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de Usuario"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="accounts.rol",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "Usuario",
            },
        ),
    ]
