# Generated by Django 5.2.7 on 2025-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="require_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Si está activado, el usuario debe usar autenticación de dos factores",
                verbose_name="Requiere 2FA",
            ),
        ),
    ]
