# Generated by Django 5.2.7 on 2025-11-19 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("correccion", "Corrección Anexada"),
                            ("parto", "Nuevo Parto"),
                            ("sistema", "Notificación del Sistema"),
                        ],
                        default="sistema",
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "Notificacion",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["receptor", "leida"],
                        name="Notificacio_recepto_011dfe_idx",
                    ),
                    models.Index(
                        fields=["-fecha_creacion"],
                        name="Notificacio_fecha_c_e5a322_idx",
                    ),
                ],
            },
        ),
    ]
